local ts = require('telescope.builtin')
vim.keymap.set('n', '<leader>tf', ts.find_files, { desc = "Open file search" })
vim.keymap.set('n', '<leader>tg', ts.git_files, { desc = "Open git file search" })
vim.keymap.set('n', '<leader>tG', function()
    ts.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = "Grep from directory without preview" })
vim.keymap.set("n", "<leader>tg", ts.live_grep, { desc = "Live grep from directory" })
